// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxwyrnhduxtsmoofjtmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4d3lybmhkdXh0c21vb2ZqdG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDY5MDEsImV4cCI6MjA2NjU4MjkwMX0.6_S6O32wogVNJMAUDBe4fYbh9GGP8zcpYxmYk1Ob8d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});